# Generated by Django 3.0 on 2020-05-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=1500)),
                ('number', models.IntegerField()),
                ('busnumber', models.IntegerField()),
                ('fare', models.IntegerField()),
            ],
        ),
    ]
